import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Carlos",
  description: "Terms of service for Mechanic Carlos, the AI car diagnostic assistant.",
  alternates: { canonical: "https://mchaniccarlos.com/terms" },
};

export default function TermsPage() {
  return (
    <main style={{
      maxWidth: '680px',
      margin: '0 auto',
      padding: '48px 24px',
      color: '#d1d5db',
      fontFamily: 'var(--font-inter), system-ui, sans-serif',
      lineHeight: 1.7
    }}>
      <h1 style={{ color: 'white', fontSize: '28px', fontWeight: 700, marginBottom: '8px' }}>
        Terms of Service
      </h1>
      <p style={{ color: '#6b7280', fontSize: '14px', marginBottom: '40px' }}>
        Last updated: May 2026
      </p>

      <h2 style={{ color: 'white', fontSize: '18px', fontWeight: 600, marginTop: '32px', marginBottom: '12px' }}>
        What Carlos is
      </h2>
      <p>
        Mechanic Carlos is an AI-powered diagnostic tool. It provides information and guidance about car problems based on symptoms and codes you describe. Carlos is not a licensed mechanic and does not provide professional automotive advice.
      </p>

      <h2 style={{ color: 'white', fontSize: '18px', fontWeight: 600, marginTop: '32px', marginBottom: '12px' }}>
        What Carlos is not
      </h2>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li>Carlos is not a substitute for a qualified mechanic</li>
        <li>Diagnoses are AI-generated estimates, not guarantees</li>
        <li>Cost estimates are approximations based on general data</li>
        <li>Always verify with a professional before making repair decisions</li>
      </ul>

      <h2 style={{ color: 'white', fontSize: '18px', fontWeight: 600, marginTop: '32px', marginBottom: '12px' }}>
        Your responsibilities
      </h2>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li>You must be 18 or older to use Carlos</li>
        <li>You are responsible for decisions made based on Carlos&apos;s output</li>
        <li>Don&apos;t use Carlos for anything illegal or harmful</li>
        <li>Don&apos;t attempt to reverse engineer or scrape the service</li>
      </ul>

      <h2 style={{ color: 'white', fontSize: '18px', fontWeight: 600, marginTop: '32px', marginBottom: '12px' }}>
        Limitation of liability
      </h2>
      <p>
        Carlos is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. To the maximum extent permitted by law, we are not liable for any direct, indirect, incidental, consequential, or special damages arising from your use of the service.
      </p>
      <p>
        <strong style={{ color: 'white' }}>AI diagnosis feature specifically:</strong> diagnoses, safety verdicts, diagnostic steps, part recommendations, and cost estimates are generated by an artificial intelligence model and may be incomplete, outdated, or wrong. We are not liable for repair costs incurred, repairs performed or deferred, vehicle damage, personal injury, or any other loss resulting from reliance on AI-generated output — including &ldquo;okay to drive&rdquo; assessments. If a diagnosis involves brakes, steering, airbags, fuel leaks, or any safety-critical system, you must have the vehicle inspected by a qualified mechanic before driving it. Our total aggregate liability for any claim shall not exceed the amount you paid us in the twelve months preceding the claim.
      </p>

      <h2 style={{ color: 'white', fontSize: '18px', fontWeight: 600, marginTop: '32px', marginBottom: '12px' }}>
        Changes to these terms
      </h2>
      <p>
        We may update these terms occasionally. Continued use of Carlos after changes means you accept the new terms.
      </p>

      <h2 style={{ color: 'white', fontSize: '18px', fontWeight: 600, marginTop: '32px', marginBottom: '12px' }}>
        Contact
      </h2>
      <p>
        Questions? Email us at mcchaniccarlossupport@gmail.com
      </p>
    </main>
  )
}
